version: "3.8"

services:
  config-server:
    build: ./config-server
    ports:
      - "8888:8888"

  eureka-server:
    build: ./eureka-server
    ports:
      - "8761:8761"
    depends_on:
      - config-server

  usuarios-servicio:
    build: ./usuarios-servicio
    ports:
      - "8081:8081"
    depends_on:
      - eureka-server
      - config-server

  asignaturas-servicio:
    build: ./asignaturas-servicio
    ports:
      - "8082:8082"
    depends_on:
      - eureka-server
      - config-server

  matriculas-servicio:
    build: ./matriculas-servicio
    ports:
      - "8083:8083"
    depends_on:
      - eureka-server
      - config-server
